---
- hosts: corda
  remote_user: vagrant
  become: True
  vars:
    corda_source: maven
    corda_version: 1.0.0
    corda_networkmap_address: '10.10.10.103'
    corda_networkmap_name: "O=Corda S.A.,L=Warsaw, C=PL"
  roles:
    - corda-ansible
